# Configuración de Redis para Urukais Klick

# Memoria máxima
maxmemory 256mb

# Política de eliminación
maxmemory-policy allkeys-lru

# Persistencia
save 900 1
save 300 10
save 60 10000

# Log
loglevel notice
